version: '2'
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heyburrito:
    image: chralp/heyburrito:latest
    ports:
      - "3333:3333"
      - "8080:8080"
    environment:
      - BOT_NAME=heyburrito
      - DATABASE_DRIVER=mongodb
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=heyburrito
      - SLACK_API_TOKEN=xoxb-540413052949-1471321759959-hLtOgin9nf4fVjUlGtbvca5h
      - "SLACK_EMOJI_INC=:avocado:"
      - "SLACK_EMOJI_INC=:avocado_rotten:"
      - SLACK_DAILY_CAP=5
      - DISABLE_EMOJI_DEC = true

    links:
      - mongodb
